# Generated by Django 3.1.1 on 2020-09-13 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CollarCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ColourCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('time', models.DateTimeField()),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('animal_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spot.animalcategory')),
                ('collar_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spot.collarcategory')),
                ('colour_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spot.colourcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('time', models.DateTimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.TextField()),
                ('animal_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spot.animalcategory')),
                ('collar_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spot.collarcategory')),
                ('colour_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spot.colourcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
