# Generated by Django 3.1.1 on 2020-09-13 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sighting',
            name='user',
        ),
        migrations.AddField(
            model_name='sighting',
            name='species',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
